---
- name: Check availability of ports
  ansible.builtin.shell: |
    lsof -i :{{ item }} > /dev/null && echo "in_use" || echo "available"
  register: lsof_check
  loop: "{{ range(32100, 32125) | list }}"  
  changed_when: false
  failed_when: false
  loop_control:
    loop_var: item
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Assign a dynamic port if one is available
  set_fact:
    dynamic_port_for_grafana: "{{ (lsof_check.results | selectattr('stdout', 'equalto', 'available') | map(attribute='item') | list | first) }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Kubectl port-forward on/for Grafana with dynamic port
  ansible.builtin.shell: KUBECONFIG={{ kubeconfig }} kubectl -n prometheus port-forward svc/prometheus-grafana "{{ dynamic_port_for_grafana }}:80" --request-timeout=30m
  async: 1800
  poll: 0
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Wait for port-forward to be available
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 30
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Set the Grafana URL
  set_fact:
    grafana_url: "http://127.0.0.1:{{ dynamic_port_for_grafana }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Check availability of ports
  ansible.builtin.shell: |
    lsof -i :{{ item }} > /dev/null && echo "in_use" || echo "available"
  register: lsof_check
  loop: "{{ range(32100, 32125) | list }}"  
  changed_when: false
  failed_when: false
  loop_control:
    loop_var: item
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Assign a dynamic port if one is available
  set_fact:
    dynamic_port_for_topology_monitor: "{{ (lsof_check.results | selectattr('stdout', 'equalto', 'available') | map(attribute='item') | list | first) }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Kubectl port-forward on/for Topology monitor with dynamic port
  ansible.builtin.shell: KUBECONFIG={{ kubeconfig }} kubectl -n kube-system port-forward svc/topology-monitor "{{ dynamic_port_for_topology_monitor }}:8080" --request-timeout=30m
  async: 1800
  poll: 0
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Wait for port-forward to be available
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 30
  when: ingress_hostname is undefined or ingress_hostname | trim == ''

- name: Set the Topology Monitor URL
  set_fact:
    topology_url: "http://127.0.0.1:{{ dynamic_port_for_topology_monitor }}"
  when: ingress_hostname is undefined or ingress_hostname | trim == ''
