sre_diagnosis_tool_task:
  description: 
    Diagnose the problem from the alert, continuing until you find all root causes of the issue. Use the tools provided to gather information to help you with diagnosis.
    Diagnosis needs to go as deep as possible. Make sure you check every entity that could possibly be related to the issue before coming to a final answer.
  expected_output: 
    Fault propagation chains indicating the independent paths along which the faults propagated and led to the alerts. Specify the root cause entity in each propagation chain.
  agent: sre_diagnosis_agent

diagnosis_json_generation_task:
  description: >
    Generate a JSON-structured diagnosis report.
  expected_output: >
    A JSON-structured diagnosis report.
  agent: sre_diagnosis_agent
    
sre_remediation_task:
  description: 
    Create and execute a remediation plan based on the incident diagnosis report. After each action, check if the alerts are resolved.
  expected_output: 
    A list of remediation plans with specific steps for mitigation.
  agent: sre_remediation_agent

remediation_json_generation_task:
  description: >
    Generate a structured JSON report on the remediation actions taken.
  expected_output: >
    A JSON-structured remediation report detailing the steps taken to mitigate the incident.
  agent: sre_remediation_agent
